version: "3"
services:
  metube:
    image: metube-local
    container_name: metube-local
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - STATE_DIR=/state
      - TEMP_DIR=/dl-tmp
      - AUDIO_DOWNLOAD_DIR=/downloads-audio
      - YTDL_OPTIONS={"download_archive":"/archive/downloaded.txt"}
    volumes:
      - /opt/metube/state:/state
      - /opt/metube/archive:/archive
      - /mnt/media-vault/Youtube:/downloads
      - /mnt/media-vault/Music/#new:/downloads-audio

